##################################################################################################
#  Hola
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: hola
  labels:
    app: hola
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hola
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hola
        version: "0.0.1"
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        - name: AB_OFF
          value: ""
        name:  wildfly
        image: hola:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10

